version: "3.9"

services:
  db:
    image: postgres:13-alpine
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  api:
    build: .
    container_name: ecommerce_api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=ecommerce
      - DB_SSLMODE=disable
      - DB_MAX_OPEN_CONNS=10
      - DB_MAX_IDLE_CONNS=5
      - DB_CONN_MAX_LIFETIME=30m
      - DB_LOG_LEVEL=info
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy
      redis:
          condition: service_healthy
    volumes:
      - .:/app
    command: sh -c "go run cmd/api/main.go"

  redis:
    image: redis:7-alpine
    container_name: ecommerce_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ecommerce_redis_gui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"
    depends_on:
      - redis
volumes:
  postgres_data: