# Base URL
@baseUrl = http://localhost:8080/api/v1

### List all products (with pagination)
# Optional query params: page, limit, category_id, is_active
GET {{baseUrl}}/products?page=1&limit=10
Content-Type: application/json

### Get product by ID
GET {{baseUrl}}/products/1
Content-Type: application/json

### Get product by slug
GET {{baseUrl}}/products/slug/new-product5525dds
Content-Type: application/json

### Create a new product
POST {{baseUrl}}/products
Content-Type: application/json

{
  "category_id": 1,
  "name": "New Product5525ddss",
  "slug": "new-product5525ddss",
  "description": "teste2",
  "is_active": true
}

### Update a product (partial update)
PUT {{baseUrl}}/products/2
Content-Type: application/json

{
  "name": "Updated Product Name",
  "description": "teste2",
  "is_active": false
}

### Delete a product
DELETE {{baseUrl}}/products/4
Content-Type: application/json

### Health check
GET http://localhost:8080/health
Content-Type: application/json

#########################################################

### List all categories
GET {{baseUrl}}/categories?page=1&limit=10
Content-Type: application/json

### Get category by ID
GET {{baseUrl}}/categories/1
Content-Type: application/json

### Get category by slug
GET {{baseUrl}}/categories/slug/teste1
Content-Type: application/json


### Create a new Category
POST {{baseUrl}}/categories
Content-Type: application/json

{
  "Name": "teste1",
  "slug": "New",
  "description": "teste1",
  "is_active": true,
  "parent_id":2
}


